### ISSUE TITLE
Filtern für Vertiefungen im Vorlesungsplan

### ISSUE THREAD

**Issue by SirTimme** [DHBWLoerrach/CampusApp#19]
Eine Möglichkeit, um die Vertiefungsfächer von dem 3ten und 5ten Semester anzugeben.
Danach soll dann der Vorlesungsplan gefiltert werden, um nur den eigenen relevanten Studiengang anzuzeigen.

**Comment by behrends** [comment]
Interessante Idee. 

Allerdings wird dies wohl kaum umzusetzen sein, da die Vertiefungsfächer nicht als solche im Outlook-Kalender gekennzeichnet sind.
