### ISSUE TITLE
App stürtzt ab bei Mensaplan Tageswechsel

### ISSUE THREAD

**Issue by quitefabulous** [DHBWLoerrach/CampusApp#2]
Schicke App, danke dafür!
Jedoch, wann immer ich im Mensaplan den Tag wechsel (ob über Swipe oder direkte Auswahl) crasht die App. Ist 100% reproduzierbar.
Außerdem wechselt der Tag nicht beim ersten Aufruf. Wenn ich auf den heuten Tag wechsel, stürzt die App ab und beim Neustart ist der richtige Tag dann ausgewählt.

Passiert auf:
Appel iPhone S (Model MKQT2ZD/A)
Version 12.1 (16B92)

Wenn du mehr Feedback brauchst gern.

**Comment by behrends** [comment]
Danke für die Rückmeldung!
Wir haben diesen Fehler inzwischen in Version 2.2.1 behoben.
