### ISSUE TITLE
Mensaplan wird nicht angezeigt

### ISSUE THREAD

**Issue by vschlegel** [DHBWLoerrach/CampusApp#4]
Plan kann nicht geladen werden. Auf https://www.swfr.de/loerrach/ kann der aktuelle Plan eingesehen werden.

**Comment by behrends** [comment]
Danke für den Hinweis! 
Das Problem liegt wohl auf Seiten der Datenschnittstelle des SWFR und wir hoffen auf eine schnelle Lösung…
