### ISSUE TITLE
IOS Darkmode Launchscreen

### ISSUE THREAD

**Issue by LouisKoenig** [DHBWLoerrach/CampusApp#40]
Wenn der Darkmode bei IOS aktiviert wird, ist der Launchscreen Background standardmäßig schwarz statt weiß.

Das DHBW Logo welches jedoch im Launchscreen hinterlegt wurde, hat einen weißen Hintergrund und passt nicht zum schwarzen Hintergrund beim Darkmode.

Lösung:

Das Logo sollte mit einem Logo ohne Hintergrund ausgetauscht werden oder der Launchscreen Hintergrund unabhängig vom Darkmode auf weiß.

**Comment by behrends** [comment]
Sollte im nächsten Release enthalten sein
